// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPNwtcSuuBZu29MUyJjj_von6qVTx_KV4',
    appId: '1:858391095462:web:8f26598e9b7f3d73e96c67',
    messagingSenderId: '858391095462',
    projectId: 'xerobuddy-54612',
    authDomain: 'xerobuddy-54612.firebaseapp.com',
    storageBucket: 'xerobuddy-54612.appspot.com',
    measurementId: 'G-MG360SDFMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFaKUauQq0O9wm0rB_vgU-kH7Z5K2diZo',
    appId: '1:858391095462:android:55909ebbee20c3b8e96c67',
    messagingSenderId: '858391095462',
    projectId: 'xerobuddy-54612',
    storageBucket: 'xerobuddy-54612.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMt4iE6FHv_vCPp6HhE0kMj4pdCHwblG0',
    appId: '1:858391095462:ios:af7da60841c71507e96c67',
    messagingSenderId: '858391095462',
    projectId: 'xerobuddy-54612',
    storageBucket: 'xerobuddy-54612.appspot.com',
    androidClientId: '858391095462-58b4fbe0bl2577v88hjjmpfn1lvld639.apps.googleusercontent.com',
    iosClientId: '858391095462-gbmfkg2t7cq44g3bdodjcoaiccsmedqp.apps.googleusercontent.com',
    iosBundleId: 'com.example.xerobuddyApp',
  );
}
